/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TatariN_174 (https://sketchfab.com/TatariN_174)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/the-tablet-eb132567326042439625b91d17429758
Title: The tablet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Tablet = (props) => {
  const { nodes, materials } = useGLTF('/models/the_tablet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['korpus.002']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.korpus2} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.zadsten} />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.ekran}
        position={[0, 0, -0.004]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.material}
        position={[0, 0, -0.067]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.582}
      />
    </group>
  )
}

export default Tablet

useGLTF.preload('/models/the_tablet.glb')
